[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ff-standings"
version = "1.0.0"
description = "Fantasy Football vs Everyone standings calculation library"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "FF App", email = "noreply@example.com" }
]
dependencies = [
  "boto3",
  "requests"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["ff_standings*"]


